### ISSUE TITLE
Bug in findColorTriplets.m?

### ISSUE THREAD

**Issue by aasharma90** [jflalonde/radiometricCalibration#3]
Dear @jflalonde 

Many thanks for your implementation and sharing the code with us. Could you please check if the following is indeed a bug in findColorTriplets.m?

`
centerEdgeColor  = reshape(centerSqColorPatch, size(centerSqColorPatch,3), size(centerSqColorPatch,1)*size(centerSqColorPatch,2));
`
I think it generates the RGB triplets incorrectly. I think what you expect is that each column contains an RGB triplet, but this will actually fill columnwise and not channelwise. 

I checked that if you do this 
`
centerEdgeColor = reshape(permute(centerSqColorPatch, [3 1 2]), [], size(centerSqColorPatch,1)*size(centerSqColorPatch,2));
`
the triplets can be formed correctly (each column contains an RGB triplet now). 

Thanks again!

**Comment by jflalonde** [comment]
Could you do a pull request for this problem? Thanks for the proposed fix.

**Comment by aasharma90** [comment]
Hi @jflalonde 

Thanks for getting back. I've created a pull request. Feel free to review it as you like. 

Best!

**Comment by jflalonde** [comment]
Thank you, I just merged your changes.
